version: "3"
services:

  otdb:
    build: .
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
